Script started on 2024-02-14 08:38:47-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
cloj    ]0;lvm5@remotel1: ~/214/labs/05/src[01;32mlvm5@remotel1[00m:[01;34m~/214/labs/05/src[00m$ scloj     clojure 


[K
Clojure 1.10.1



[K
user=> 

[K
user=> 

[K
user=> (fn [x][x] (+ x x)(+ x x) )
user=> (fn [x] (+ x x) )
user=> [K(fn [x] (+ x x) )



[K
#object[user$eval136$fn__137 0x5328a9c1 "user$eval136$fn__137@5328a9c1"]

user=> 

[K
user=> 

[K
user=> ((fn [x][x] (+ x x)(+ x x))
user=> ((fn [x] (+ x x)) 21)
user=> ((fn [x] (+ x x)) 21)
user=> [K((fn [x] (+ x x)) 21)

42

user=> 

[K
user=> 

[K
user=> ((fn [x y][x y] (+ (* x x)(* x x) (* y y)(* y y))(+ (* x x) (* y y)))
user=> ((fn [x y] (+ (* x x) (* y y))) 3 4)
user=> ((fn [x y] (+ (* x x) (* y y))) 3 4)
user=> [K((fn [x y] (+ (* x x) (* y y))) 3 4)

25

user=> 

[K
user=> 

[K
user=> 



[K
]0;lvm5@remotel1: ~/214/labs/05/src[01;32mlvm5@remotel1[00m:[01;34m~/214/labs/05/src[00m$ exit

Script done on 2024-02-14 08:40:09-05:00 [COMMAND_EXIT_CODE="0"]
