Script started on 2024-02-15 18:23:20-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ clojure


[K
Clojure 1.10.1



[K
user=> 

[K
user=> 

user=> [K((fn [x y z] (+ x y z)) 1 2 3)

6

user=> 

user=> [K((fn [x] (nil? x)) nil)

true

user=> 

[K
user=> 
user=> [8@((fn [x] (nil? x)) nil)[1P-3)
user=> [K((fn [x] (nil? x)) -3)

false

user=> 

[K
user=> 

user=> [K((fn [] 17.2))

17.2

user=> 

[K
user=> 

[K
user=> 



[K
]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ exit

Script done on 2024-02-15 18:24:04-05:00 [COMMAND_EXIT_CODE="0"]
