Script started on 2024-02-15 18:31:49-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (def squareSquare #(* %1 %1)(* %1 %1))user=> (def squareSquare #(* %1 %1)) 2)([1@([K((def squareSquare #(* %1 %1)) 2)
4
user=> [Kuser=> [Kuser=> ((def squareSquare #(* %1 %1)) 2)[1@-user=> [K((def squareSquare #(* %1 %1)) -2)
4
user=> [Kuser=> [Kuser=> ((def squareSquare #(* %1 %1)) -2)[1P)3)user=> [K((def squareSquare #(* %1 %1)) -3)
9
user=> [Kuser=> [Kuser=> ((def squareSquare #(* %1 %1)) -3)[1Puser=> [K((def squareSquare #(* %1 %1)) 3)
9
user=> [Kuser=> [Kuser=> 
[K]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ exit

Script done on 2024-02-15 18:32:22-05:00 [COMMAND_EXIT_CODE="0"]
