Script started on 2024-02-15 18:54:35-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ clojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> (def negate (fn [seq][seq] (map #(- %)(- %) seq)(map #(- %) seq))user=> (def negate (fn [seq] (map #(- %) seq)))user=> (def negate (fn [seq] (map #(- %) seq)))user=> [K(def negate (fn [seq] (map #(- %) seq)))
[K#'user/negate
user=> [Kuser=> [Kuser=> ( (negate [-1 2 -3][-1 2 -3])user=> (negate [-1 2 -3])user=> [K(negate [-1 2 -3])
(1 -2 3)
user=> [Kuser=> [Kuser=> (negate [4 -5 6][4 -5 6])user=> (negate [4 -5 6])user=> [K(negate [4 -5 6])
(-4 5 -6)
user=> [Kuser=> [Kuser=> 
[K]0;lvm5@remotel2: ~/214/labs/05/src[01;32mlvm5@remotel2[00m:[01;34m~/214/labs/05/src[00m$ exit

Script done on 2024-02-15 18:55:08-05:00 [COMMAND_EXIT_CODE="0"]
